services:
  - type: web
    name: lol-page
    env: python
    region: frankfurt   # możesz zmienić np. "oregon" albo "singapore"
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    plan: free

    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4


