app = "lol-pages"
fly volumes create dbdata --size 1 --region waw



[build]
  builder = "paketobuildpacks/builder:base"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[processes]
  app = "gunicorn app:app --bind 0.0.0.0:8080"

[[mounts]]
  source = "dbdata"
  destination = "/data"






